# Generated by Django 3.1.4 on 2021-02-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demisto_id', models.IntegerField(blank=True, null=True)),
                ('ticket_title', models.TextField(blank=True, null=True)),
                ('ticket_created', models.DateTimeField(blank=True, null=True)),
                ('ticket_priority', models.IntegerField(blank=True, null=True)),
                ('ticket_priority2', models.IntegerField(blank=True, null=True)),
                ('ticket_status', models.TextField(blank=True, null=True)),
                ('ticket_owner', models.TextField(blank=True, null=True)),
                ('ticket_sourceip', models.TextField(blank=True, db_column='ticket_sourceIP', null=True)),
                ('ticket_details', models.TextField(blank=True, null=True)),
                ('ticket_vib_owner', models.TextField(blank=True, null=True)),
                ('ticket_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'intership',
                'managed': False,
            },
        ),
    ]
