# Generated by Django 3.1.4 on 2021-02-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intership',
            options={'managed': False, 'verbose_name_plural': 'intership'},
        ),
    ]
