# Generated by Django 3.1.4 on 2021-02-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_id',
            new_name='id',
        ),
    ]
