# Generated by Django 3.1.4 on 2021-02-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210210_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
