# Generated by Django 3.1.4 on 2021-02-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
