# Generated by Django 3.1.4 on 2021-02-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
